name: sensor_viewer
description: Bridge Sensor Monitoring

version: 1.0.2+102

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  toast: ^0.1.5
  intl: ^0.17.0
  package_info: ^0.4.0+16
  http: ^0.12.0+4
  flutter_speed_dial: ^1.2.5
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.4.2
  device_info: ^0.4.2+1

  sqflite:
  path:

  screen: ^0.0.5
  mysql1: ^0.17.1
  mvc_pattern: ^6.1.3+2
  firebase_messaging: 6.0.13
  global_configuration: 1.5.0
  charts_flutter: ^0.11.0
  flutter_webview_plugin: ^0.3.11
  cached_network_image: 2.2.0
  image_picker: ^0.6.7+4
  location: ^3.0.2
  charcode: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: 'assets/images/appicon.jpg'
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/images/
    - assets/images/sample/
    - assets/images/bridge/

